/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let numberSection = 1;

  const handleNavigation = (direction: number) => {
    numberSection = numberSection + direction;

    if (numberSection < 1) numberSection = 1;
    else if (numberSection > 3) numberSection = 3;

    if (typeof document !== 'undefined') {
      const sectionsCounter = document.getElementById('sections-counter');
      const bar = document.getElementById('bar');
      const section = document.getElementById(`section-${numberSection}`);

      if (sectionsCounter && bar && section) {
        sectionsCounter.innerHTML = `${numberSection}/3`;
        bar.style.height = `${numberSection * 34}%`;
        section.scrollIntoView();
      }
    }
  }

  useEffect(() => {
    window.addEventListener("wheel", event => {
      const delta = Math.sign(event.deltaY);
      handleNavigation(delta);
    });

    return () => {
      window.removeEventListener("wheel", () => { });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="background"></div>

        <header className='header'>
          <nav>
            <Link href="/">Artista</Link>
            <Link href="/">Releases</Link>
            <Link href="/">Vídeos</Link>
            <Link href="/">Contato</Link>
          </nav>
        </header>

        <div className='explanation'> 
          <p>THIS IS</p>
        </div>

        <div className='name'> 
          <h1>JHONNY</h1>
          <h2>SAN</h2>
          <h3>TA</h3>
          <h4>NNA</h4>
        </div>

        <aside className="navigation">
          <p id="sections-counter">1/3</p>
          <div className="progress-bar">
            <span id="bar"></span>
          </div>
          <button type="button" onClick={() => handleNavigation(-1)}>
            <img src="/icons/arrow-up.svg" alt="" />
          </button>
          <button type="button" onClick={() => handleNavigation(1)}>
            <img src="/icons/arrow-down.svg" alt="" />
          </button>
        </aside>

        <section className='images'>
          <section id="section-1">
            <img className="fones left" src="/jhonny-1.png" alt="Fone da esquerda" />
          </section>

          <section id="section-2">
            <img className="fones" src="/jhonny-2.png" alt="Fone da direita" />
          </section>

          <section id="section-3">
            <img className="fones" src="/jhonny-3.png" alt="Fone da direita" />
          </section>
        </section>

        <footer className="content">

        </footer>
      </div>
    </>
  )
}
