/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { motion as m, useMotionValue, useSpring } from 'framer-motion'
import Link from 'next/link';

const draw = {
  hidden: { pathLength: 0, opacity: 0 },
  visible: (i: number) => {
    const delay = 1 + i * 0.5;
    return {
      pathLength: 1,
      opacity: 1,
      transition: {
        pathLength: { delay, type: "spring", duration: 1.5, bounce: 0 },
        opacity: { delay, duration: 0.01 }
      }
    };
  }
};

export default function Home() {
  const [play, setPlay] = useState(false)

  const cursorX = useMotionValue(-200)
  const cursorY = useMotionValue(-200)

  const springConfig = { damping: 25, stiffness: 700 };
  const cursorXSpring = useSpring(cursorX, springConfig);
  const cursorYSpring = useSpring(cursorY, springConfig);

  useEffect(() => {
    const moveCursor = (e: MouseEvent) => {
      cursorX.set(e.clientX + 8)
      cursorY.set(e.clientY + 8)
    }
    window.addEventListener('mousemove', moveCursor)
    return () => {
      window.removeEventListener('mousemove', moveCursor)
    }
  }, [cursorX, cursorY])

  const toggleVideo = () => {
    const video = document.getElementById('jhonny') as HTMLVideoElement
    const playButton = document.getElementById('playButton') as HTMLButtonElement

    if (!video || !playButton) return;

    if (video.paused) {
      video.play()
      setPlay(true)
    } else {
      video.pause()
      setPlay(false)
    }
  }

  return (
    <>
      <Head>
        <title>Jhonny Santanna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <m.div
          className="cursor"
          style={{
            translateX: cursorXSpring,
            translateY: cursorYSpring,
          }}
        />
        <header>
          <div className='logo'>
            <h1>Jhonny Santanna</h1>
          </div>
          <div className='decoration'>
            <div className='doted'></div>
            <div className='doted'></div>
            <div className='doted'></div>
            <div className='doted'></div>
            <div className='doted'></div>
            <div className='doted'></div>
          </div>
        </header>

        <main>
          <figure>
            <div className='gradient radial-gradient'></div>
            <div className='gradient gradient-1'></div>
            <div className='gradient gradient-2'></div>
            <video id="jhonny" autoPlay={true} loop muted={false} preload="auto" poster="video-thumb.png" src="Camisa-Manchada.mp4"></video>
            <div className='play' onClick={toggleVideo}>
              <m.button id="playButton" whileHover={{ scale: 1.02 }}>
                {!play && (
                  <m.svg
                    initial="hidden"
                    animate="visible"
                    xmlns="http://www.w3.org/2000/svg"
                    width="44"
                    height="44"
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="#ffffff"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <m.path variants={draw} stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <m.path variants={draw} d="M7 4v16l13 -8z" />
                  </m.svg>
                )}
                {play && (
                  <m.svg
                    initial="hidden"
                    animate="visible"
                    xmlns="http://www.w3.org/2000/svg"
                    width="44"
                    height="44"
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="#ffffff"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <m.path variants={draw} stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <m.rect variants={draw} x="6" y="5" width="4" height="14" rx="1" />
                    <m.rect variants={draw} x="14" y="5" width="4" height="14" rx="1" />
                  </m.svg>
                )}
              </m.button>
            </div>
          </figure>

        </main>

        <footer>
          <nav className='info'>
            <Link href="/music">Music</Link>
            <Link href="/event">Events</Link>
            <Link href="/contact">Contact Me</Link>
          </nav>
          <div className="separator">
            <div></div>
          </div>
          <nav className='social'>
            <a href="https://www.instagram.com/cantorjhonnysantanna/" target="_blank" rel="noreferrer">
              <svg width="25" height="25" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <g data-name="Layer 2">
                  <g data-name="twitter">
                    <polyline points="0 0 24 0 24 24 0 24" opacity="0" />
                    <path fill='#fff' d="M8.08 20A11.07 11.07 0 0 0 19.52 9 8.09 8.09 0 0 0 21 6.16a.30.44 0 0 0-.62-.51 1.88 1.88 0 0 1-2.16-.38 3.89 3.89 0 0 0-5.58-.17A4.13 4.13 0 0 0 11.49 9C8.14 9.2 5.84 7.61 4 5.43a.43.43 0 0 0-.75.24 9.68 9.68 0 0 0 4.6 10.05A6.73 6.73 0 0 1 3.38 18a.45.45 0 0 0-.14.84A11 11 0 0 0 8.08 20" />
                  </g>
                </g>
              </svg>
            </a>
            <a href="https://www.facebook.com/jhonny.santanna.7" target="_blank" rel="noreferrer">
              <svg
                width="25" height="25"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24">
                <g data-name="Layer 2">
                  <g data-name="facebook">
                    <rect width="24" height="24" transform="rotate(180 12 12)" opacity="0" />
                    <path fill='#fff' d="M17 3.5a.5.5 0 0 0-.5-.5H14a4.77 4.77 0 0 0-5 4.5v2.7H6.5a.5.5 0 0 0-.5.5v2.6a.5.5 0 0 0 .5.5H9v6.7a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-6.7h2.62a.5.5 0 0 0 .49-.37l.72-2.6a.5.5 0 0 0-.48-.63H13V7.5a1 1 0 0 1 1-.9h2.5a.5.5 0 0 0 .5-.5z" />
                  </g>
                </g>
              </svg>
            </a>
          </nav>
        </footer>
      </div>
    </>
  )
}

